#include <hive/protocol/blockchain_configuration.hpp>
#include <hive/protocol/types.hpp>
#include <hive/protocol/asset.hpp>

namespace hive
{
  namespace protocol
  {
    namespace blockchain_configuration
    {

    #ifdef IS_TEST_NET
      configuration_pv_key_t hive_init_private_key{fc::ecc::private_key::regenerate(fc::sha256::hash(std::string("init_key")))};
      configuration_version_t hive_blockchain_version{version(1, 26, 0)};
      configuration_str_t hive_init_public_key_str{hive::protocol::public_key_type(hive_init_private_key.get().get_public_key())};
      configuration_hash_t steem_chain_id{fc::sha256::hash("testnet")};
      configuration_hash_t def_hive_chain_id{fc::sha256::hash("testnet")};
      configuration_str_t hive_address_prefix{"TST"};
      configuration_timepoint_t hive_genesis_time{fc::time_point_sec(1451606400)};
      configuration_timepoint_t hive_mining_time{fc::time_point_sec(1451606400)};
      configuration_int_t hive_cashout_window_seconds{60 * 60};
      configuration_int_t hive_cashout_window_seconds_pre_hf12{hive_cashout_window_seconds.get()};
      configuration_int_t hive_cashout_window_seconds_pre_hf17{hive_cashout_window_seconds.get()};
      configuration_int_t hive_second_cashout_window{60 * 60};
      configuration_int_t hive_max_cashout_window_seconds{60 * 60 * 24};
      configuration_time_t hive_upvote_lockout_hf7{fc::minutes(1)};
      configuration_uint_t hive_upvote_lockout_seconds{60u * 5};
      configuration_time_t hive_upvote_lockout_hf17{fc::minutes(5)};
      configuration_int_t hive_min_account_creation_fee{0};
      configuration_bigint_t hive_max_account_creation_fee{int64_t(1000000000)};
      configuration_time_t hive_owner_auth_recovery_period{fc::seconds(60)};
      configuration_time_t hive_account_recovery_request_expiration_period{fc::seconds(12)};
      configuration_time_t hive_owner_update_limit{fc::seconds(0)};
      configuration_uint_t hive_owner_auth_history_tracking_start_block_num{1u};
      configuration_bigint_t hive_init_supply{int64_t(250) * int64_t(1000000) * int64_t(1000)};
      configuration_bigint_t hive_hbd_init_supply{int64_t(7) * int64_t(1000000) * int64_t(1000)};
      configuration_uint_t testnet_block_limit{3000000u};
      configuration_int_t hive_proposal_maintenance_period{3600};
      configuration_int_t hive_proposal_maintenance_cleanup{60 * 60 * 24 * 1};
      configuration_int_t hive_daily_proposal_maintenance_period{60 * 60};
      configuration_time_t hive_governance_vote_expiration_period{fc::days(20)};
      configuration_int_t hive_global_remove_threshold{20};
    #else
      configuration_version_t hive_blockchain_version{version(1, 25, 8)};
      configuration_str_t hive_init_public_key_str{"STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX"};
      configuration_hash_t steem_chain_id{fc::sha256()};
      configuration_hash_t def_hive_chain_id{fc::sha256::hash("beeab0de00000000000000000000000000000000000000000000000000000000")};
      configuration_str_t hive_address_prefix{"STM"};
      configuration_timepoint_t hive_genesis_time{fc::time_point_sec(1458835200)};
      configuration_timepoint_t hive_mining_time{fc::time_point_sec(1458838800)};
      configuration_int_t hive_cashout_window_seconds_pre_hf12{60 * 60 * 24};
      configuration_int_t hive_cashout_window_seconds_pre_hf17{60 * 60 * 12};
      configuration_int_t hive_cashout_window_seconds{60 * 60 * 24 * 7};
      configuration_int_t hive_second_cashout_window{60 * 60 * 24 * 30};
      configuration_int_t hive_max_cashout_window_seconds{60 * 60 * 24 * 14};
      configuration_time_t hive_upvote_lockout_hf7{fc::minutes(1)};
      configuration_uint_t hive_upvote_lockout_seconds{60u * 60 * 12};
      configuration_time_t hive_upvote_lockout_hf17{fc::hours(12)};
      configuration_int_t hive_min_account_creation_fee{1};
      configuration_bigint_t hive_max_account_creation_fee{int64_t(1000000000)};
      configuration_time_t hive_owner_auth_recovery_period{fc::days(30)};
      configuration_time_t hive_account_recovery_request_expiration_period{fc::days(1)};
      configuration_time_t hive_owner_update_limit{fc::minutes(60)};
      configuration_uint_t hive_owner_auth_history_tracking_start_block_num{3186477u};
      configuration_bigint_t hive_init_supply{int64_t(0)};
      configuration_bigint_t hive_hbd_init_supply{int64_t(0)};
      configuration_int_t hive_proposal_maintenance_period{3600};
      configuration_int_t hive_proposal_maintenance_cleanup{60 * 60 * 24 * 1};
      configuration_int_t hive_daily_proposal_maintenance_period{HIVE_ONE_DAY_SECONDS};
      configuration_time_t hive_governance_vote_expiration_period{fc::days(365)};
      configuration_int_t hive_global_remove_threshold{200};
    #endif
      configuration_asset_symbol_t vests_symbol{hive::protocol::asset_symbol_type::from_asset_num(HIVE_ASSET_NUM_VESTS)};
      configuration_asset_symbol_t hive_symbol{hive::protocol::asset_symbol_type::from_asset_num(HIVE_ASSET_NUM_HIVE)};
      configuration_asset_symbol_t hbd_symbol{hive::protocol::asset_symbol_type::from_asset_num(HIVE_ASSET_NUM_HBD)};
      configuration_hardfork_version_t hive_blockchain_hardfork_version{hive_blockchain_version.get()};
      configuration_uint_t hive_start_vesting_block{hive_blocks_per_day * 7u};
      configuration_uint_t hive_start_miner_voting_block{hive_blocks_per_day * 30u};
      configuration_str_t hive_init_miner_name{"initminer"};
      configuration_int_t hive_num_init_miners{1};
      configuration_timepoint_t hive_init_time{fc::time_point_sec()};
      configuration_int_t hive_hardfork_required_witnesses{17};
      configuration_uint_t hive_max_time_until_expiration{60u * 60};
      configuration_uint_t hive_max_memo_size{2048u};
      configuration_int_t hive_vesting_withdraw_intervals_pre_hf_16{104};
      configuration_int_t hive_vesting_withdraw_intervals{13};
      configuration_int_t hive_vesting_withdraw_interval_seconds{60 * 60 * 24 * 7};
      configuration_int_t hive_max_withdraw_routes{10};
      configuration_int_t hive_max_pending_transfers{255};
      configuration_time_t hive_savings_withdraw_time{fc::days(3)};
      configuration_int_t hive_savings_withdraw_request_limit{100};
      configuration_int_t hive_max_vote_changes{5};
      configuration_int_t hive_reverse_auction_window_seconds_hf6{60 * 30};
      configuration_int_t hive_reverse_auction_window_seconds_hf20{60 * 15};
      configuration_int_t hive_reverse_auction_window_seconds_hf21{60 * 5};
      configuration_int_t hive_early_voting_seconds_hf25{24 * 60 * 60};
      configuration_int_t hive_mid_voting_seconds_hf25{48 * 60 * 60};
      configuration_int_t hive_min_vote_interval_sec{3};
      configuration_int_t hive_vote_dust_threshold{50000000};
      configuration_uint_t hive_downvote_pool_percent_hf21{25 * hive_1_percent};
      configuration_int_t hive_delayed_voting_total_interval_seconds{60 * 60 * 24 * 30};
      configuration_int_t hive_delayed_voting_interval_seconds{60 * 60 * 24 * 1};
      configuration_time_t hive_min_root_comment_interval{fc::seconds(60 * 5)};
      configuration_time_t hive_min_reply_interval{fc::seconds(20)};
      configuration_time_t hive_min_reply_interval_hf20{fc::seconds(3)};
      configuration_time_t hive_min_comment_edit_interval{fc::seconds(3)};
      configuration_uint_t hive_post_average_window{60 * 60 * 24u};
      configuration_ubigint_t hive_post_weight_constant{uint64_t(4 * hive_100_percent) * (4 * hive_100_percent)};
      configuration_int_t hive_max_account_witness_votes{30};
      configuration_uint_t hive_default_hbd_interest_rate{10u * hive_1_percent};
      configuration_int_t hive_inflation_rate_start_percent{978};
      configuration_int_t hive_inflation_rate_stop_percent{95};
      configuration_int_t hive_inflation_narrowing_period{250000};
      configuration_uint_t hive_content_reward_percent_hf16{75u * hive_1_percent};
      configuration_uint_t hive_vesting_fund_percent_hf16{15u * hive_1_percent};
      configuration_int_t hive_proposal_fund_percent_hf0{0};
      configuration_uint_t hive_content_reward_percent_hf21{65u * hive_1_percent};
      configuration_uint_t hive_proposal_fund_percent_hf21{10 * hive_1_percent};
      configuration_hugeint_t hive_hf21_convergent_linear_recent_claims{fc::uint128_t(0, 503600561838938636ull)};
      configuration_hugeint_t hive_content_constant_hf21{fc::uint128_t(0, 2000000000000ull)};
      configuration_uint_t hive_miner_pay_percent{hive_1_percent};
      configuration_int_t hive_max_ration_decay_rate{1000000};
      configuration_int_t hive_bandwidth_average_window_seconds{60 * 60 * 24 * 7};
      configuration_ubigint_t hive_bandwidth_precision{uint64_t(1000000)};
      configuration_int_t hive_max_comment_depth_pre_hf17{6};
      configuration_int_t hive_max_comment_depth{0xffff};
      configuration_int_t hive_soft_max_comment_depth{0xff};
      configuration_int_t hive_max_reserve_ratio{20000};
      configuration_int_t hive_create_account_with_hive_modifier{30};
      configuration_int_t hive_create_account_delegation_ratio{5};
      configuration_time_t hive_create_account_delegation_time{fc::days(30)};
      configuration_asset_t hive_mining_reward{1000, hive_symbol.get()};
      configuration_uint_t hive_equihash_n{140u};
      configuration_uint_t hive_equihash_k{6u};
      configuration_time_t hive_liquidity_timeout_sec{fc::seconds(60 * 60 * 24 * 7)};
      configuration_time_t hive_min_liquidity_reward_period_sec{fc::seconds(60)};
      configuration_int_t hive_liquidity_reward_blocks{hive_liquidity_reward_period_sec / hive_block_interval};
      configuration_asset_t hive_min_liquidity_reward{1000 * hive_liquidity_reward_blocks.get(), hive_symbol.get()};
      configuration_asset_t hive_min_content_reward{hive_mining_reward.get()};
      configuration_asset_t hive_min_curate_reward{hive_mining_reward.get()};
      configuration_asset_t hive_min_producer_reward{hive_mining_reward.get()};
      configuration_asset_t hive_min_pow_reward{hive_mining_reward.get()};
      configuration_asset_t hive_active_challenge_fee{2000, hive_symbol.get()};
      configuration_asset_t hive_owner_challenge_fee{30000, hive_symbol.get()};
      configuration_time_t hive_active_challenge_cooldown{fc::days(1)};
      configuration_time_t hive_owner_challenge_cooldown{fc::days(1)};
      configuration_str_t hive_post_reward_fund_name{"post"};
      configuration_str_t hive_comment_reward_fund_name{"comment"};
      configuration_time_t hive_recent_rshares_decay_time_hf17{fc::days(30)};
      configuration_time_t hive_recent_rshares_decay_time_hf19{fc::days(15)};
      configuration_hugeint_t hive_content_constant_hf0{uint128_t(uint64_t(2000000000000ll))};
      configuration_asset_t hive_min_payout_hbd{20, hbd_symbol.get()};
      configuration_uint_t hive_hbd_stop_percent_hf14{5u * hive_1_percent};
      configuration_uint_t hive_hbd_stop_percent_hf20{10u * hive_1_percent};
      configuration_uint_t hive_hbd_start_percent_hf14{2u * hive_1_percent};
      configuration_uint_t hive_hbd_start_percent_hf20{9u * hive_1_percent};
      configuration_uint_t hive_max_account_name_length{16u};
      configuration_uint_t hive_min_permlink_length{0u};
      configuration_uint_t hive_max_permlink_length{256u};
      configuration_uint_t hive_max_witness_url_length{2048u};
      configuration_bigint_t hive_max_share_supply{int64_t(1000000000000000ll)};
      configuration_bigint_t hive_max_satoshis{int64_t(4611686018427387903ll)};
      configuration_int_t hive_max_sig_check_depth{2};
      configuration_int_t hive_max_sig_check_accounts{125};
      configuration_int_t hive_min_transaction_size_limit{1024};
      configuration_ubigint_t hive_seconds_per_year{uint64_t(60 * 60 * 24 * 365ll)};
      configuration_int_t hive_hbd_interest_compound_interval_sec{60 * 60 * 24 * 30};
      configuration_int_t hive_max_transaction_size{1024 * 64};
      configuration_uint_t hive_min_block_size_limit{ static_cast<uint32_t>(hive_max_transaction_size.get()) };
      configuration_uint_t hive_max_block_size{hive_max_transaction_size.get() * hive_block_interval * 2000u};
      configuration_uint_t hive_soft_max_block_size{2u * 1024 * 1024};
      configuration_uint_t hive_min_block_size{115u};
      configuration_int_t hive_blocks_per_hour{60 * 60 / hive_block_interval};
      configuration_int_t hive_feed_interval_blocks{hive_blocks_per_hour.get()};
      configuration_int_t hive_feed_history_window_pre_hf_16{24 * 7};
      configuration_uint_t def_hive_feed_history_window{12u * 7};
      configuration_int_t hive_max_feed_age_seconds{60 * 60 * 24 * 7};
      configuration_uint_t hive_min_feeds{hive_max_witnesses / 3u};
      configuration_time_t hive_conversion_delay_pre_hf_16{fc::days(7)};
      configuration_time_t def_hive_conversion_delay{fc::hours(def_hive_feed_history_window.get())};
      configuration_int_t hive_min_undo_history{10};
      configuration_uint_t hive_max_undo_history{10000u};
      configuration_int_t hive_min_transaction_expiration_limit{hive_block_interval * 5};
      configuration_ubigint_t hive_blockchain_precision{uint64_t(1000)};
      configuration_int_t hive_blockchain_precision_digits{3};
      configuration_ubigint_t hive_max_instance_id{uint64_t(-1) >> 16};
      configuration_uint_t hive_max_authority_membership{40u};
      configuration_int_t hive_max_asset_whitelist_authorities{10};
      configuration_int_t hive_max_url_length{127};
      configuration_hugeint_t hive_virtual_schedule_lap_length{fc::uint128(uint64_t(-1))};
      configuration_hugeint_t hive_virtual_schedule_lap_length2{fc::uint128::max_value()};
      configuration_int_t hive_initial_vote_power_rate{40};
      configuration_int_t hive_reduced_vote_power_rate{10};
      configuration_int_t hive_max_limit_order_expiration{60 * 60 * 24 * 28};
      configuration_int_t hive_delegation_return_period_hf0{hive_cashout_window_seconds.get()};
      configuration_int_t hive_delegation_return_period_hf20{hive_voting_mana_regeneration_seconds};
      configuration_int_t hive_rd_max_decay_bits{32};
      configuration_uint_t hive_rd_min_decay{uint32_t(1) << hive_rd_min_decay_bits};
      configuration_int_t hive_rd_min_budget{1};
      configuration_uint_t hive_rd_max_decay{uint32_t(0xFFFFFFFF)};
      configuration_uint_t hive_account_subsidy_precision{hive_100_percent};
      configuration_uint_t hive_witness_subsidy_budget_percent{125u * hive_1_percent};
      configuration_uint_t hive_witness_subsidy_decay_percent{hive_max_witnesses * hive_100_percent};
      configuration_int_t hive_default_account_subsidy_decay{347321};
      configuration_int_t hive_default_account_subsidy_budget{797};
      configuration_uint_t hive_decay_backstop_percent{90u * hive_1_percent};
      configuration_uint_t hive_block_generation_postponed_tx_limit{5u};
      configuration_time_t hive_pending_transaction_execution_limit{fc::milliseconds(200)};
      configuration_uint_t hive_custom_op_id_max_length{32u};
      configuration_uint_t hive_custom_op_data_max_length{8192u};
      configuration_uint_t hive_beneficiary_limit{128u};
      configuration_uint_t hive_comment_title_limit{256u};
      configuration_int_t hive_one_day_seconds{60 * 60 * 24};
      configuration_str_t hive_miner_account{"miners"};
      configuration_str_t hive_null_account{"null"};
      configuration_str_t hive_temp_account{"temp"};
      configuration_str_t hive_proxy_to_self_account{""};
      configuration_accountname_t hive_root_post_parent{account_name_type()};
      configuration_str_t obsolete_treasury_account{"steem.dao"};
      configuration_str_t new_hive_treasury_account{"hive.fund"};
      configuration_ubigint_t hive_treasury_fee{10 * hive_blockchain_precision.get()};
      configuration_uint_t hive_proposal_subject_max_length{80u};
      configuration_uint_t hive_proposal_max_ids_number{5u};
      configuration_int_t hive_proposal_fee_increase_days{60};
      configuration_uint_t hive_proposal_fee_increase_days_sec{60u * 60 * 24 * hive_proposal_fee_increase_days.get()};
      configuration_ubigint_t hive_proposal_fee_increase_amount{1 * hive_blockchain_precision.get()};
      configuration_uint_t hive_proposal_conversion_rate{5 * hive_1_basis_point};
#ifdef HIVE_ENABLE_SMT
      configuration_int_t smt_max_votable_assets{2};
      configuration_int_t smt_vesting_withdraw_interval_seconds{60 * 60 * 24 * 7};
      configuration_int_t smt_upvote_lockout{60 * 60 * 12};
      configuration_int_t smt_emission_min_interval_seconds{60 * 60 * 6};
      configuration_uint_t smt_emit_indefinitely{std::numeric_limits<uint32_t>::max()};
      configuration_int_t smt_max_nominal_votes_per_day{1000};
      configuration_uint_t smt_max_votes_per_regeneration{(smt_max_nominal_votes_per_day.get() * smt_vesting_withdraw_interval_seconds.get()) / 86400};
      configuration_int_t smt_default_votes_per_regen_period{50};
      configuration_uint_t smt_default_percent_curation_rewards{25u * hive_1_percent};
#endif

    }
  }
} // hive::protocol::blockchain_configuration
